#!/bin/sh
# claude-rename hook runner — finds node regardless of shell/PATH setup
# Generated by install.sh. Re-run installer to update.

# Find node — try PATH first, then common version manager / install locations
NODE_BIN="$(command -v node 2>/dev/null)"

# NVM (most common version manager)
if [ -z "$NODE_BIN" ] && [ -d "$HOME/.nvm/versions/node" ]; then
  NODE_BIN="$(ls -1d "$HOME"/.nvm/versions/node/*/bin/node 2>/dev/null | tail -1)"
fi

# fnm
if [ -z "$NODE_BIN" ] && [ -d "$HOME/.fnm/node-versions" ]; then
  NODE_BIN="$(ls -1d "$HOME"/.fnm/node-versions/*/installation/bin/node 2>/dev/null | tail -1)"
fi
if [ -z "$NODE_BIN" ] && [ -d "$HOME/Library/Application Support/fnm/node-versions" ]; then
  NODE_BIN="$(ls -1d "$HOME/Library/Application Support/fnm/node-versions"/*/installation/bin/node 2>/dev/null | tail -1)"
fi

# volta
if [ -z "$NODE_BIN" ] && [ -x "$HOME/.volta/bin/node" ]; then
  NODE_BIN="$HOME/.volta/bin/node"
fi

# Homebrew (Apple Silicon + Intel) and system
if [ -z "$NODE_BIN" ]; then
  for p in /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do
    if [ -x "$p" ]; then NODE_BIN="$p"; break; fi
  done
fi

# Not found — fail silently so we never block Claude Code
if [ -z "$NODE_BIN" ]; then
  echo '{"continue":true,"suppressOutput":true}'
  exit 0
fi

exec "$NODE_BIN" "$HOME/.claude/hooks/claude-rename.mjs" "$@"
